# Generated by Django 5.1.7 on 2025-03-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('credit_hours', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackEnd.department')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='roadmap_posters/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='BackEnd.department')),
                ('semester1', models.ManyToManyField(blank=True, related_name='semester1', to='BackEnd.subject')),
                ('semester2', models.ManyToManyField(blank=True, related_name='semester2', to='BackEnd.subject')),
                ('semester3', models.ManyToManyField(blank=True, related_name='semester3', to='BackEnd.subject')),
                ('semester4', models.ManyToManyField(blank=True, related_name='semester4', to='BackEnd.subject')),
                ('semester5', models.ManyToManyField(blank=True, related_name='semester5', to='BackEnd.subject')),
                ('semester6', models.ManyToManyField(blank=True, related_name='semester6', to='BackEnd.subject')),
                ('semester7', models.ManyToManyField(blank=True, related_name='semester7', to='BackEnd.subject')),
                ('semester8', models.ManyToManyField(blank=True, related_name='semester8', to='BackEnd.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='professor_pics/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200, null=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='professors', to='BackEnd.subject')),
            ],
        ),
    ]
